config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api , defaults: { format: :json } do
    namespace :v1 do
      post 'users/sign_in' => 'users#login'
      get 'posts' => 'posts#index'
      get 'comments' => 'comments#index'
      post 'comments/create' => 'comments#create'
    end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  root 'users#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { in: 1..250 }
  validates :likesCounter, numericality: { greater_than_or_equal_to: 0 }
  validates :commentsCounter, numericality: { greater_than_or_equal_to: 0 }

  def self.recent_comments(id)
    Comment.where(post_id: id).limit(5)
  end

  def self.all_comments(id)
    Comment.where(post_id: id)
  end

  def self.count_post(id)
    user = User.find(id)
    user.postsCounter = Post.where(user_id: id).count
    user.save
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        if request.headers['X-AUTH-TOKEN']
          @user = User.find_by_api_token(request.headers['X-AUTH-TOKEN'])
          @posts = Post.where(user_id: @user.id)
          render json: { success: true, message: 'Loaded all posts', data: { posts: @posts } }, status: :ok
        else
          respond_to do |format|
            format.json { render json: 'please sign in or add the token', status: :ok }
          end
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ActionController::Base
  load_and_authorize_resource
  before_action :authenticate_user!
  def index
    @id = params[:user_id]
    @user = User.find(@id)
    @posts = User.all_post(@id)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def create
    @user = User.find(params[:user_id])
    add_post = @user.posts.new(post_params)
    add_post.commentsCounter = 0
    add_post.likesCounter = 0
    respond_to do |format|
      format.html do
        if add_post.save
          Post.count_post(params[:user_id])
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_url
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, locals: { post: add_post }
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @post.destroy
    @user.postsCounter -= 1
    @user.save
    redirect_to("/users/#{current_user.id}/posts/")
    flash[:success] = 'Comment was deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "partials/user", user: @user %>

    <% @posts.includes(:comments).each do |post| %>
    <%= link_to 'posts/' + post.id.to_s, :remote => true do %>

    <%= render "partials/post", post: post %>
    <% end %>

    <%= render "partials/comment", post: post %>
    

    <% if can? :manage, post %>
    <%= button_to "Delete", user_post_path(@user.id, post.id), :method => :delete, class: "btn btn-primary" %>
    <% end %>

    <% end %>

  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <h1>Create a Post</h1>

  <%= form_with model: @post, url: user_posts_path do |f| %>
  
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

  </body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="post-heading">
        <div class="flex-post">
            <p><strong><%=@post.title%></strong> by <strong><%=@user.name%></strong></p>
            <div class="flex-comment">
                <p>Comments:  <%=@post.commentsCounter%></p>
                <p>Likes:  <%=@post.likesCounter%></p>
            </div>
        </div>
        <p><%=@post.text%></p>
    </div>

    <div class="comments">
        <%Post.all_comments(@post.id).each do |comment|%>
        <p><strong><%=@user.name%>:</strong> <%=comment.text%></p>
        
        <% if can? :manage, comment %>
        <%= button_to "Delete", user_post_comment_path(@user.id, @post.id, comment.id), :method => :delete, class: "btn btn-primary"%>
        <% end %>

        <% end %>
    </div>

    <div class="space"></div>

  <h2>Add a comment</h2>

  <%= form_with model: @comment, url: user_post_comments_path(@user.id, @post.id) do |f| %>

  <div class="mb-3">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

    <div class="space"></div>

  <h2>Add a Like</h2>

  <%= form_with model: @like, url: user_post_likes_path(@user.id, @post.id) do |f| %>

  <div class="mb-3">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
  
  <% end %>

  </body>
</html>